[buildPlans.IosevkaDgMono]
family = "Iosevka DG Mono"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaDgMono.ligations]
enables = [
    "center-ops",
    "center-op-trigger-plus-minus-l",
    "center-op-trigger-plus-minus-r",
    "center-op-trigger-equal-l",
    "center-op-trigger-equal-r",
    "kern-dotty",
    "kern-bars",
]

[buildPlans.IosevkaDgMono.variants.design]
one = "base"
two = "curly-neck-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "dotted"
capital-a = "straight-top-serifed"
capital-c = "unilateral-serifed"
capital-d = "more-rounded-serifless"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-serifless-capped"
capital-j = "serifed-both-sides"
capital-l = "motion-serifed"
capital-p = "closed-serifed"
capital-q = "crossing-curly-tailed"
capital-s = "unilateral-serifed"
capital-t = "serifed"
capital-y = "straight-base-serifed"
capital-z = "straight-serifed"
a = "double-storey-serifless"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothed-top-serifed"
e = "rounded"
f = "flat-hook-serifed-crossbar-at-x-height"
g = "double-storey"
h = "straight-top-left-serifed"
j = "flat-hook-serifed"
k = "straight-top-left-serifed"
m = "short-leg-top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-serifed"
q = "straight-bottom-serifed"
r = "corner-hooked-serifed"
t = "flat-hook-short-neck2"
u = "toothed-serifless"
y = "straight-turn-serifless"
z = "straight-serifed"
long-s = "flat-hook-bottom-serifed"
capital-thorn = "motion-serifed"
lower-thorn = "serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothed-serifless"
lower-upsilon = "straight-serifed"
lower-psi = "serifed"
cyrl-capital-ka = "symmetric-connected-top-left-serifed"
cyrl-ka = "symmetric-connected-top-left-serifed"
cyrl-em = "hanging-motion-serifed"
cyrl-en = "top-left-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-serifed"
cyrl-u = "straight-turn-serifless"
asterisk = "penta-low"
underscore = "above-baseline"
brace = "straight"
ampersand = "et-toothed"
at = "fourfold"
percent = "rings-continuous-slash-also-connected"
pilcrow = "low"

[buildPlans.IosevkaDgMono.variants.italic]
one = "base"
two = "curly-neck-serifless"
five = "oblique-arched-serifless"
six = "open-contour"
seven = "bend-serifed"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "dotted"
capital-a = "straight-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothed-serifless-capped"
capital-j = "serifed-both-sides"
capital-l = "motion-serifed"
capital-p = "closed-serifed"
capital-q = "open-swash"
capital-r = "straight-top-left-serifed"
capital-s = "unilateral-serifed"
capital-t = "serifed"
capital-y = "straight-base-serifed"
capital-z = "straight-serifed"
a = "single-storey-tailed"
b = "toothed-motion-serifed"
c = "unilateral-inward-serifed"
d = "tailed-serifed"
e = "rounded"
f = "flat-hook-extended"
g = "single-storey-serifless"
h = "straight-top-left-serifed"
j = "serifed"
k = "diagonal-tailed-cursive-top-left-serifed"
m = "short-leg-top-left-serifed"
n = "straight-top-left-serifed"
p = "eared-motion-serifed"
q = "straight-serifless"
r = "top-serifed"
t = "bent-hook-short-neck2"
u = "toothed-motion-serifed"
v = "straight-serifless"
w = "rounded-vertical-sides-serifless"
x = "semi-chancery-straight-serifless"
y = "cursive-serifless"
z = "curly-serifed"
long-s = "flat-hook-descending-middle-serifed-xh"
capital-thorn = "serifed"
lower-thorn = "motion-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "tailed-serifless"
lower-upsilon = "straight-serifed"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "serifed"
cyrl-capital-ka = "symmetric-connected-serifed"
cyrl-ka = "symmetric-connected-top-left-serifed"
cyrl-em = "hanging-motion-serifed"
cyrl-capital-en = "serifed"
cyrl-en = "top-left-serifed"
cyrl-capital-er = "closed-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "straight-turn-serifed"
cyrl-u = "straight-turn-serifless"
cyrl-che = "tailed"
cyrl-capital-ya = "straight-serifed"
cyrl-ya = "straight-tailed-serifless"
asterisk = "penta-low"
underscore = "above-baseline"
brace = "straight"
ampersand = "lower-open"
at = "fourfold"
percent = "rings-continuous-slash-also-connected"
pilcrow = "low"

[buildPlans.IosevkaDgMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaDgMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaDgMono.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
